version: "3.5"
services:
  build-server:
    image: "composer:latest"
    volumes:
      - ../server:/app
      - server-volume:/var/www/html
    networks:
      - "dashnet"
    command: composer install
  build-client:
    image: "node:11-alpine"
    working_dir: /app
    volumes:
      - ../client:/app
      - client-volume:/app
    networks:
      - "dashnet"
    command: yarn build
  server:
    image: "php:7.1-apache"
    ports:
      - 9091:80
    volumes:
      - ../server/:/var/www/
      - ../server/public/index.php:/var/www/html/index.php
      - server-volume:/var/www/html
    networks:
      - "dashnet"
  client:
    build: client
    image: containerdash/client
    working_dir: /app
    ports:
      - 9090:8080
    volumes:
      - ../client:/app
      - client-volume:/app
    networks:
      - "dashnet"
networks:
  dashnet:
volumes:
  server-volume:
  client-volume:
