version: "3"
services:
  server:
    image: "php:7.1-apache"
    ports:
      - 9091:80
    volumes:
      - ../server/:/var/www/
      - ../server/public/:/var/www/html
  client:
    build: client
    image: containerdash/client
    working_dir: /app
    ports:
      - 9090:8080
    volumes:
      - ../client:/app
