version: "3"
services:
  server-dev-build:
    image: "composer:latest"
    volumes:
      - ../server:/app
      - server-dev-volume:/var/www/html
    networks:
      - "dashnet-dev"
    command: composer install
  server-dev:
    depends_on:
      - server-dev-build
    image: "php:7.1-apache"
    ports:
      - 9081:80
    volumes:
      - ../server/:/var/www/
      - ../server/public/index.php:/var/www/html/index.php
      - server-dev-volume:/var/www/html
    networks:
      - "dashnet-dev"
  client-dev:
    depends_on:
      - server-dev-build
      - server-dev
    image: "node:11-alpine"
    working_dir: /app
    ports:
      - 9080:8080
    volumes:
      - ../client:/app
      - client-dev-volume:/app
    networks:
      - "dashnet-dev"
    command: yarn serve --watch
networks:
  dashnet-dev:
volumes:
  server-dev-volume:
  client-dev-volume:
