version: "3"
services:
  build-server:
    image: "composer:latest"
    volumes:
      - ../server:/app
    command: composer install
  build-client:
    image: "node:11-alpine"
    working_dir: /app
    volumes:
      - ../client:/app
    command: yarn build
